final Map<String, String> enTranslation = {
  "skip": "Skip >",
  "chosetheroute": "Choose The Route",
  "loremipsumissimplydummytextoftheprintingandtypesettingindustry":
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
  "next": "Next",
  "requestride": "Request ride",
  "itisalongestablishedfactthatareaderwillbedistractedbythereadablecontentofapagewhenlookingatitslayout":
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
  "getyourtaxi": "Get your Taxi",
  "ifyouaregoingtouseapassageofloremipsumyouneedtobesurethereisntanythingembarrassinghiddeninthemiddleoftext":
      "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text.",
  "saveyourtime": "Save Your Time",
  "alltheloremipsumgeneratorsontheinternettendtorepeatpredefinedchunksasnecessarymakingthisthefirsttruegeneratorontheinternet":
      "All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
  "start": "Start",
  "login": "Log In",
  "signup": "Sign Up",
  "welcomeback": "Welcome back!",
  "registerinbyenteringyouraccountdetails":
      "Register in by entering your account details.",
  "username": "User Name",
  "password": "Password ...",
  "passwrd": "Password",
  "forgetpassword": "Forget Password?",
  "rememberme": "Remember me",
  "orloginwith": "Or login with ",
  "loginn": "Login",
  "fullname": "Full Name",
  "emailaddress": "e-mail Address",
  "number": "Number",
  "verifyphone": "Verify Phone",
  "phonenumber": "Phone Number",
  "pleaseconfirmyourcountrycodeandenteryourphonenumber:":
      "Please confirm your country code and enter your phone number :",
  "sendcode": "Send Code",
  "verification": "Verification",
  "code": "Code",
  "verificationcodewassentto": "Verification code was sent to",
  "resendcodein": "Resend code in ",
  "resend": "Resend",
  "findpassword": "Find Password",
  "options": "Options",
  "pleaseselectoptiontosendlinkresetpassword":
      "Please select option to send link reset password",
  "resetviaemail": "Reset via email",
  "ifyouhaveemaillinkedtoaccount": "If you have email linked to account",
  "resetviasms": "Reset via SMS",
  "recovery": "Recovery",
  "ifyouhavenumberlinkedtoaccount": "If you have number linked to acount",
  "pleaseenteryouremailtorecoveryourpassword":
      "Please enter your email to recover your password",
  "sendlink": "Send Link",
  "reset": "Reset",
  "createstrongandsecurepasswordthatprotectyouraccount":
      "Create strong and secure password that protect your account",
  "save": "Save",
  "search": "Search",
  "whereto": "Where to?",
  "customize": "Customize",
  "newtrip": "New trip",
  "tapforlocation": "Tap for location ",
  "home": "Home",
  "work": "Work",
  "allowyourlocation": "Allow your location",
  "wewillneedyourlocationtogiveyoubetterexperience":
      "We will need your location to give you better experience",
  "notnow": "Not now",
  "oksure": "Ok Sure",
  "whereareyou": "Where are you?",
  "pickoff": "Pick Off",
  "whereyouwanttogo": "Where you want to go?",
  "selectaddress": "Select Address",
  "pickuppoint": "Pickup point",
  "recent": "Recent",
  "savedplaces": "Saved Places",
  "favoriteplace": "Favorite Place",
  "placename": "Place Name",
  "placeaddress": "Place Address",
  "saveplace": "Save Place",
  "chooseatrip": "Choose a trip",
  "selectcar": "Select car",
  "bike": "Bike",
  "standard": "Standard",
  "permium": "Permium",
  "nearbie": "nearbie",
  "booknow": "Book Now",
  "searchingfordriver": "Searching for Driver",
  "searchingride": "Searching Ride",
  "itmaytakesometimes": "It may take some times",
  "driver": "Driver",
  "slidetocancel": ">> Slide To Cancel ",
  "arriving": "Arriving",
  "skodaoctavia": "Skoda Octavia.",
  "price": "Price",
  "payout": "Payout",
  "online": "Online ",
  "cash": "Cash",
  "paymentmethod": "Payment Method :",
  "bankaccount": "Bank Account",
  "promocode:": "Promo Code :",
  "promocodeoptional": "Promo Code (Optional)",
  "proceedtopay": "Proceed to pay",
  "ratedriver": "Rate Driver",
  "thankyou": "Thank you!",
  "pleaserateyourtrip": "Please rate your trip",
  "writeyourmessagehere": "Write your message here ...",
  "shareyourmessagewithothertaxipassenger":
      "Share your message with other taxi passenger.",
  "whatsyourmood": "What's your mood!",
  "aboutthistrip": "about this trip?",
  "submit": "Submit",
  "wow5star": "Wow 5 star!",
  "doyouwanttoantadditionaltipforjoesmith":
      "Do you want to ant additional tip for joe smith",
  "no": "No ",
  "paytip": "Pay Tip",
  "sendtip": "Send Tip",
  "sendtojoe": "Send to Joe",
  "canceltrip": "Cancel Trip",
  "pleaseselectthereasonforcancellation:":
      "Please select the reason for cancellation:",
  "waitingforlongtime": "Waiting for long time",
  "wrongaddressshown": "Wrong address shown",
  "thepriceisnotreasonable": "The price is not reasonable",
  "rideisn’there": "Ride isn’t here",
  "others": "Others",
  "wallet": "Wallet",
  "history": "History",
  "payment": "Payment",
  "becomeadriver": "Become a Driver",
  "settings": "Settings",
  "invitefriends": "Invite Friends",
  "nonotificationyet": "No  Notification Yet",
  "notifications": "Notifications",
  "languages": "Languages",
  "whenyougetnotificaiontheyllshowupِhere":
      "When you get notificaion, they'll show upِhere",
  "return": "Return",
  "searchnotifications": "Search Notifications ...",
  "today": "Today",
  "promotion": "Promotion",
  "invtefriendsyougot25gift": "Invte friends - you got 25 gift!",
  "newpaymentmethod": "New payment method",
  "hasbeenaddedsuccessfuly": "has been added successfuly",
  "system": "System",
  "thankyouyourtransactionis": "Thank you! your transaction is ...",
  "joesmith": "Joe Smith",
  "helloithinkyouleftyourbag": "Hello, I think you left your bag ...",
  "faq": "FAQ",
  "pineapplerelatedquestions": "Pineapple related questions",
  "loremipsumdolorsitconsecteturadipiscingelitintegerpretiumelitidmollisornare":
      "Lorem ipsum dolor sit  consectetur adipiscing elit. Integer pretium elit id mollis ornare. ",
  "systemrelatedquestions:": "System related questions:",
  "supportrelatedquestions:": "Support related questions:",
  "mypromotions": "My promotions",
  "enteryourpromotioncod": "Enter your promotion cod",
  "saveuptooffthebaserateofweekrental":
      "Save up to 30% off the base rate of week rental",
  "validuntil": "Valid until",
  "mywallet": "My Wallet",
  "defultpaymentmethod": "Defult Payment Method",
  "balance": "Balance",
  "paymentmethods": "Payment Methods",
  "coupon": "Coupon",
  "transactions": "Transactions",
  "whenyourfrindssignupwithyourlinkyou’llbothgetcharge":
      "When your frinds sign up with your link you’ll both get \$20 charge",
  "congratulation": "Congratulation",
  "reward": "Reward",
  "youreceivedanawardthroughyourfriendmembership":
      "You received an award through your friend membership!",
  "recive": "Recive",
  "ridehistory": "Ride History",
  "completed": "Completed",
  "canceled": "Canceled",
  "thisweek": "This week",
  "paymenthistory": "Payment history ",
  "paid": "Paid",
  "fee": "Fee",
  "date": "Date ",
  "total": "Total :",
  "driverdetails": "Driver details",
  "point": "Point",
  "trips": "Trips",
  "years": "Years",
  "membersince": "Member since",
  "carmodel": "Car Model",
  "platenumber": "Plate number",
  "list": "List",
  "map": "Map",
  "messages": "Messages",
  "account": "Account",
  "personalinformation": "Personal Information",
  "location": "Location",
  "inforamtion": "Information",
  "discountnotifications": "Discount Notifications",
  "editaccount": "Edit Account",
  "selectaccount": "Select account",
  "transaction": "Transaction",
  "defaultcard": "Default Card",
  "setthiscardasyourdefault": "Set this card as your default",
  "contactlesspayment": "Contactless Payment",
  "activecontactlesspayment": "Active contactless payment ",
  "addnewcard": "Add New Card",
  "addyourdebitcreaditcard": "Add your debit/credit card",
  "cardholdername": "Card-Holder name",
  "expirydate": "Expiry Date",
  "cardnumber": "Card Number",
  "cvv": "CVV",
  "add": "Add",
  "myprofile": "My Profile",
  "changepassword": "Change password",
  "change": "Change",
  "currentpassword": "Current Password...",
  "newpassword": "New Password...",
  "confirmpassword": "पासवर्ड की पुष्टि कीजिये...",
  "selectyourpreferredlanguage": "Select your preferred Language",
  "choosethelanguage": "Choose the language",
  "confirmlanguage": "Confirm Language",
  "english": "English",
  "hindi": "Hindi",
  "pleaseenteravalidemailaddress": "Please enter a valid email address",
  "pleaseenteravalidpassword": "Please enter a valid password",
  "thepasswordmustcontainatleastsixcharacter":
      "The password must contain at least six character",
  "pleaseenteravalidfullname": "Please enter a valid fullname",
  "pleaseenteraplace": "Please enter a Place",
  "pleaseenteraplaceaddress": "Please enter a Place Address",
  "camera": "Camera",
  "gallery": "Gallery",
  "link": "link",
};
