final Map<String, String> hiTranslation = {
  "skip": "छोड़ें >",
  "chosetheroute": "मार्ग चुना",
  "loremipsumissimplydummytextoftheprintingandtypesettingindustry":
      "Lorem Ipsum मुद्रण और टाइपसेटिंग उद्योग का बस डमी पाठ है।",
  "next": "अगला",
  "requestride": "अनुरोध सवारी",
  "itisalongestablishedfactthatareaderwillbedistractedbythereadablecontentofapagewhenlookingatitslayout":
      "यह एक लंबे समय से स्थापित तथ्य है कि एक पाठक अपने लेआउट को देखते समय किसी पृष्ठ की पठनीय सामग्री से विचलित हो जाएगा।",
  "getyourtaxi": "अपनी टैक्सी प्राप्त करें",
  "ifyouaregoingtouseapassageofloremipsumyouneedtobesurethereisntanythingembarrassinghiddeninthemiddleoftext":
      "यदि आप लोरेम आईपीएसम के पारित होने जा रहे हैं, तो आपको यह सुनिश्चित करने की ज़रूरत है कि पाठ के बीच में कुछ भी शर्मनाक नहीं है।",
  "saveyourtime": "अपना समय बचाओ",
  "alltheloremipsumgeneratorsontheinternettendtorepeatpredefinedchunksasnecessarymakingthisthefirsttruegeneratorontheinternet":
      "इंटरनेट पर सभी लोरम आईपीएसयूएम जनरेटर पूर्वनिर्धारित हिस्सों को आवश्यकतानुसार दोहराते हैं, जो इसे इंटरनेट पर पहला सच्चा जनरेटर बनाते हैं।",
  "start": "शुरू",
  "login": "लॉग इन करें",
  "signup": "साइन अप करें",
  "welcomeback": "वापसी पर स्वागत है!",
  "registerinbyenteringyouraccountdetails":
      "अपने खाते के विवरण दर्ज करके रजिस्टर करें।",
  "username": "उपयोगकर्ता नाम",
  "password": "कुंजिका ...",
  "passwrd": "कुंजिका",
  "forgetpassword": "पासवर्ड भूल गए?",
  "rememberme": "मुझे याद रखना",
  "orloginwith": "या लॉग इन करें",
  "loginn": "लॉग इन करें",
  "fullname": "पूरा नाम",
  "emailaddress": "ईमेल पता",
  "number": "संख्या",
  "verifyphone": "फोन सत्यापित करें",
  "phonenumber": "फ़ोन नंबर",
  "pleaseconfirmyourcountrycodeandenteryourphonenumber:":
      "कृपया अपने देश कोड की पुष्टि करें और अपना फ़ोन नंबर दर्ज करें:",
  "sendcode": "कोड भेजो",
  "verification": "सत्यापन",
  "code": "कोड",
  "verificationcodewassentto": "सत्यापन कोड को भेजा गया था",
  "resendcodein": "में कोड भेजना",
  "resend": "पुन: भेजें",
  "findpassword": "पासवर्ड पता करो",
  "options": "विकल्प",
  "pleaseselectoptiontosendlinkresetpassword":
      "कृपया लिंक रीसेट पासवर्ड भेजने के लिए विकल्प का चयन करें",
  "resetviaemail": "ईमेल के माध्यम से रीसेट करें",
  "ifyouhaveemaillinkedtoaccount": "यदि आपके पास खाता से जुड़ा ईमेल है",
  "ifyouhavenumberlinkedtoaccount": "यदि आपके पास खाता से जुड़ा हुआ है",
  "resetviasms": "एसएमएस के माध्यम से रीसेट करें",
  "recovery": "स्वास्थ्य लाभ",
  "pleaseenteryouremailtorecoveryourpassword":
      "कृपया अपना पासवर्ड पुनर्प्राप्त करने के लिए अपना ईमेल दर्ज करें",
  "sendlink": "कड़ी भेजें",
  "reset": "रीसेट",
  "createstrongandsecurepasswordthatprotectyouraccount":
      "अपने खाते की सुरक्षा वाले मजबूत और सुरक्षित पासवर्ड बनाएं",
  "save": "सहेजें",
  "search": "खोज",
  "languages": "भाषाओं",
  "whereto": "जहां?",
  "customize": "अनुकूलित करें",
  "newtrip": "नई यात्रा",
  "tapforlocation": "स्थान के लिए टैप करें",
  "home": "घर",
  "work": "काम",
  "allowyourlocation": "अपने स्थान की अनुमति दें",
  "wewillneedyourlocationtogiveyoubetterexperience":
      "आपको बेहतर अनुभव देने के लिए हमें आपके स्थान की आवश्यकता होगी",
  "notnow": "अभी नहीं",
  "oksure": "यकीनन ठीक",
  "whereareyou": "आप कहाँ हैं?",
  "pickoff": "उठा ले",
  "whereyouwanttogo": "आप कहाँ जाना चाहते हो?",
  "selectaddress": "पता का चयन करें",
  "pickuppoint": "पिक अप बिंदु",
  "recent": "हालिया",
  "savedplaces": "सहेजे गए स्थान",
  "favoriteplace": "पसंदीदा स्थान",
  "placename": "जगह का नाम",
  "placeaddress": "पता",
  "saveplace": "स्थान बचाओ",
  "chooseatrip": "एक यात्रा चुनें",
  "selectcar": "कार का चयन करें",
  "bike": "साइकिल",
  "standard": "मानक",
  "permium": "परमियम",
  "nearbie": "निकट",
  "booknow": "अभी बुक करें",
  "searchingfordriver": "चालक के लिए खोज",
  "searchingride": "खोज सवारी",
  "itmaytakesometimes": "इसमें कुछ समय लग सकता है",
  "driver": "चालक",
  "slidetocancel": " >> रद्द करने के लिए स्लाइड",
  "arriving": "पहुंचने",
  "skodaoctavia": "स्कोडा ऑक्टाविया।",
  "price": "कीमत",
  "payout": "भुगतान",
  "online": "ऑनलाइन",
  "cash": "नकद",
  "paymentmethod": "भुगतान विधि :",
  "bankaccount": "बैंक खाता",
  "promocode:": "प्रचार कोड :",
  "promocodeoptional": "प्रोमो कोड (वैकल्पिक)",
  "proceedtopay": "चुकाने के लिए कार्रवाई शुरू करो",
  "ratedriver": "दर चालक",
  "thankyou": "शुक्रिया!",
  "pleaserateyourtrip": "कृपया अपनी यात्रा को रेट करें",
  "writeyourmessagehere": "यहां अपना संदेश लिखें ...",
  "shareyourmessagewithothertaxipassenger":
      "अन्य टैक्सी यात्री के साथ अपना संदेश साझा करें।",
  "whatsyourmood": "तुम्हारा मूड कैसा है!",
  "aboutthistrip": "इस यात्रा के बारे में?",
  "submit": "प्रस्तुत करना",
  "wow5star": "वाह 5 सितारा!",
  "doyouwanttoantadditionaltipforjoesmith":
      "क्या आप जो स्मिथ के लिए चींटी अतिरिक्त टिप चाहते हैं",
  "no": "नहीं",
  "paytip": "पे टिप",
  "sendtip": "टिप भेजें",
  "sendtojoe": "जो को भेजें",
  "canceltrip": "यात्रा रद्द करें",
  "pleaseselectthereasonforcancellation:": "कृपया रद्द करने का कारण चुनें:",
  "waitingforlongtime": "लंबे समय तक इंतजार कर रहा है",
  "wrongaddressshown": "गलत पता दिखाया गया",
  "thepriceisnotreasonable": "मूल्य उचित नहीं है",
  "rideisn’there": "सवारी यहाँ नहीं है",
  "others": "अन्य",
  "wallet": "बटुआ",
  "history": "इतिहास",
  "payment": "भुगतान",
  "becomeadriver": "एक ड्राइवर बनें",
  "settings": "समायोजन",
  "invitefriends": "मित्रों को आमंत्रित करें",
  "nonotificationyet": "अभी तक कोई अधिसूचना नहीं",
  "notifications": "अधिसूचनाएं",
  "whenyougetnotificaiontheyllshowupِhere":
      "जब आप अधिसिषेक प्राप्त करते हैं, तो वे यहां दिखाएंगे",
  "return": "वापसी",
  "searchnotifications": "खोज अधिसूचनाएं ...",
  "today": "आज",
  "promotion": "पदोन्नति",
  "invtefriendsyougot25gift": "आविडे दोस्तों - आपको 25 उपहार मिला!",
  "newpaymentmethod": "नई भुगतान विधि",
  "hasbeenaddedsuccessfuly": "सफल जोड़ा गया है",
  "system": "प्रणाली",
  "thankyouyourtransactionis": "शुक्रिया! आपका लेनदेन है ...",
  "joesmith": "जो स्मिथ",
  "helloithinkyouleftyourbag":
      "हैलो, मुझे लगता है कि आपने अपना बैग छोड़ दिया ...",
  "faq": "सामान्य प्रश्न",
  "pineapplerelatedquestions": "अनानास संबंधित प्रश्न",
  "loremipsumdolorsitconsecteturadipiscingelitintegerpretiumelitidmollisornare":
      "Lorem Ipsum Dolor Sit Consectutur elit elit। पूर्णांक प्रीटियम एलिट आईडी मोलिस ऑर्नेयर।",
  "systemrelatedquestions:": "सिस्टम संबंधित प्रश्न:",
  "supportrelatedquestions:": "संबंधित प्रश्नों का समर्थन करें:",
  "mypromotions": "मेरे प्रचार",
  "enteryourpromotioncod": "अपना प्रचार कोड दर्ज करें",
  "saveuptooffthebaserateofweekrental":
      "सप्ताह के किराये की आधार दर से 30% तक बचाएं",
  "validuntil": "तब तक वैध",
  "mywallet": "मेरा बटुआ",
  "defultpaymentmethod": "भुगतान विधि",
  "balance": "संतुलन",
  "paymentmethods": "भुगतान की विधि",
  "coupon": "कूपन",
  "transactions": "लेनदेन",
  "whenyourfrindssignupwithyourlinkyou’llbothgetcharge":
      "जब आपके फ्रिंड्स आपके लिंक के साथ साइन अप करते हैं तो आप दोनों को \$ 20 शुल्क प्राप्त करेंगे",
  "congratulation": "बधाई",
  "reward": "इनाम",
  "youreceivedanawardthroughyourfriendmembership":
      "आपको अपने मित्र सदस्यता के माध्यम से एक पुरस्कार मिला!",
  "recive": "पुनः प्राप्त करना",
  "ridehistory": "सवारी इतिहास",
  "completed": "पुरा होना",
  "canceled": "रद्द",
  "thisweek": "इस सप्ताह",
  "paymenthistory": "भुगतान इतिहास",
  "paid": "भुगतान किया गया",
  "fee": "शुल्क",
  "date": "तारीख",
  "total": "संपूर्ण :",
  "driverdetails": "ड्राइवर का विवरण",
  "point": "बिंदु",
  "trips": "ट्रिप्स",
  "years": "वर्षों",
  "membersince": "से सदस्य",
  "carmodel": "कार के मॉडल",
  "platenumber": "थाली संख्या",
  "list": "सूची",
  "map": "नक्शा",
  "messages": "संदेशों",
  "account": "हेतु",
  "personalinformation": "व्यक्तिगत जानकारी",
  "location": "स्थान",
  "inforamtion": "इन्फोरम्प्शन",
  "discountnotifications": "छूट अधिसूचनाएं",
  "editaccount": "खाता संपादित करें",
  "selectaccount": "खाता चुनें",
  "transaction": "लेन - देन",
  "defaultcard": "डिफ़ॉल्ट कार्ड",
  "setthiscardasyourdefault": "इस कार्ड को अपने डिफ़ॉल्ट के रूप में सेट करें",
  "contactlesspayment": "संपर्क रहित भुगतान",
  "activecontactlesspayment": "सक्रिय संपर्क रहित भुगतान",
  "addnewcard": "नया कार्ड जोड़ें",
  "addyourdebitcreaditcard": "अपना डेबिट / क्रैडिट कार्ड जोड़ें",
  "cardholdername": "कार्डधारक का नाम",
  "cardnumber": "कार्ड संख्या",
  "expirydate": "समाप्ति तिथि",
  "cvv": "सीवीवी",
  "add": "जोड़ें",
  "myprofile": "मेरी प्रोफाइल",
  "changepassword": "पासवर्ड बदलें",
  "change": "परिवर्तन",
  "currentpassword": "वर्तमान पासवर्ड...",
  "newpassword": "नया पासवर्ड...",
  "confirmpassword": "पासवर्ड की पुष्टि कीजिये...",
  "selectyourpreferredlanguage": "अपनी पसंदीदा भाषा का चयन करें",
  "choosethelanguage": "भाषा चुनें",
  "confirmlanguage": "भाषा की पुष्टि करें",
  "english": "अंग्रेज़ी",
  "hindi": "हिन्दी",
  "pleaseenteravalidemailaddress": "कृपया एक वैध ई - मेल एड्रेस डालें",
  "pleaseenteravalidpassword": "कृपया एक वैध पासवर्ड दर्ज करें",
  "thepasswordmustcontainatleastsixcharacter":
      "पासवर्ड में कम से कम छह वर्ण होना चाहिए",
  "pleaseenteravalidfullname": "कृपया एक मान्य पूर्ण नाम दर्ज करें",
  "pleaseenteraplace": "कृपया एक जगह दर्ज करें",
  "pleaseenteraplaceaddress": "कृपया एक जगह का पता दर्ज करें",
  "camera": "कैमरा",
  "gallery": "गेलरी",
  "link": "संपर्क",
};
